- name: Call Supabase Edge Function with a Random Query
        env:
          PROMPTS_JSON: |
            [
              "What are the core business areas of Quadrate Tech Solutions (quadrate.lk)?",
              "List the key technology stacks used by Quadrate Tech Solutions (quadrate.lk).",
              "Summarize the main products and services offered by Quadrate Tech Solutions (quadrate.lk).",
              "Who are the primary target customers for Quadrate Tech Solutions (quadrate.lk)?",
              "Provide an overview of recent projects completed by Quadrate Tech Solutions (quadrate.lk)."
            ]
        run: |
          # Read the prompts and pick one at random using jq.
          # The fix is changing "random()" to "random".
          RANDOM_PROMPT=$(echo "${PROMPTS_JSON}" | jq -r '.[random * length | floor]')
          
          echo "Selected Prompt: $RANDOM_PROMPT"
          
          # Construct the JSON payload using the selected prompt
          JSON_PAYLOAD=$(jq -n --arg prompt "$RANDOM_PROMPT" '{prompt: $prompt}')
          
          # Make the API call
          curl -L -X POST 'https://npwbxlvcfrawolebzawn.supabase.co/functions/v1/quadrate-contact' \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD"
